<a href="https://colab.research.google.com/github/harttu/docs/blob/master/Data_Import_and_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import imageio
import torch

## Bobby

In [10]:
!wget -o /dev/null https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch4/image-dog/bobby.jpg

In [4]:
img_arr = imageio.imread("bobby.jpg")

In [5]:
img_arr.shape

(720, 1280, 3)

In [6]:
img = torch.from_numpy(img_arr)
out = img.permute(2,0,1)

In [7]:
img.shape

torch.Size([720, 1280, 3])

In [60]:
out.shape

torch.Size([3, 720, 1280])

In [61]:
!rm *.png

In [62]:
!wget -o /dev/null https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch4/image-cats/cat1.png
!wget -o /dev/null https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch4/image-cats/cat2.png
#!wget -o /dev/null https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch4/image-cats/cat3.png

In [63]:
batch_size = 2
batch = torch.zeros(batch_size, 3 , 256, 256, dtype=torch.uint8)

In [64]:
img_arr = imageio.imread('cat1.png')
img_t = torch.from_numpy(img_arr)
  

Alkuperäinen formaatti: 256 riviä, 256 saraketta, 3 arvoa ( RGB )

In [65]:
img_t.shape

torch.Size([256, 256, 3])

permute(2,0,1) <- uusi dimensioiden järjestys. Ekanan viimeinen(2) sitten normaalista 0 ja 1

In [66]:
img_t = img_t.permute(2,0,1)

In [67]:
img_t.shape

torch.Size([3, 256, 256])

In [68]:
img_t[:3,:,:125].shape #ottaa kaikki kanavat, 256 riviä ja 125 saraketta

torch.Size([3, 256, 125])

In [69]:
import os
data_dir = '.'
filenames = [ name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == '.png' ]

for i, filename in enumerate(filenames):
  img_arr = imageio.imread(os.path.join(data_dir, filename))
  img_t = torch.from_numpy(img_arr)
  img_t = img_t.permute(2,0,1)
  img_t = img_t[:3] # tiputtaa mahdollisen alpha kanavan pois
  batch[i] = img_t

In [70]:
batch = batch.float()
batch /= 256.0

In [71]:
batch.shape

torch.Size([2, 3, 256, 256])

In [72]:
batch[0].shape

torch.Size([3, 256, 256])

In [74]:
batch[:,0].shape

torch.Size([2, 256, 256])

In [39]:
batch[:,:,0].shape

torch.Size([3, 3, 256])

In [35]:
n_channels = batch.shape[1]
for c in range(n_channels): # jokaiselle kanavalle
  mean = torch.mean(batch[:, c])
  std = torch.std(batch[:, c])
  batch[:,c] = (batch[:, c] - mean) / std

## Wine

In [75]:
!wget -o /dev/null https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch4/tabular-wine/winequality-white.csv

In [78]:
import csv
import numpy as np

wine_path = "winequality-white.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32,delimiter=';',skiprows=1)
wineq_numpy 

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [80]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [81]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [82]:
data = wineq[:,:-1]
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [83]:
target = wineq[:,-1]
target, target.shape

(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))

In [84]:
target = wineq[:,-1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [101]:
target.shape

torch.Size([4898])

In [100]:
target.unsqueeze(1)

tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]])

In [88]:
target_onehot = torch.zeros(target.shape[0],10)
target_onehot.shape

torch.Size([4898, 10])

In [89]:
target_onehot.scatter_(1, target.unsqueeze(1), 1.0 )

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [90]:
x = torch.tensor([1, 2, 3, 4])

In [108]:
src = torch.arange(2, 12).reshape((2, 5))
src

tensor([[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11]])

In [111]:
index = torch.tensor([[0, 1, 2, 0]])
index

tensor([[0, 1, 2, 0]])

In [112]:
torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src) # index on että mihin riveille arvoja src:sta laitetaan

tensor([[2, 0, 0, 5, 0],
        [0, 3, 0, 0, 0],
        [0, 0, 4, 0, 0]])

In [113]:
torch.zeros(3, 5, dtype=src.dtype).scatter_(1, index, src) # index on että mihin riveille arvoja src:sta laitetaan

tensor([[5, 3, 4, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [117]:
index = torch.tensor([[0, 1, 2], [0, 1, 4]])
index

tensor([[0, 1, 2],
        [0, 1, 4]])

In [118]:
torch.zeros(3, 5, dtype=src.dtype).scatter_(1, index, src) # syöttää tässä järjestyksessä

tensor([[2, 3, 4, 0, 0],
        [7, 8, 0, 0, 9],
        [0, 0, 0, 0, 0]])

In [92]:
x

tensor([1, 2, 3, 4])

In [ ]:
>>> index = torch.tensor([[0, 1, 2], [0, 1, 4]])
>>> torch.zeros(3, 5, dtype=src.dtype).scatter_(1, index, src)

### Squeeze

Returns a tensor with all the dimensions of input of size 1 removed.

For example, if input is of shape: (A×1×B×C×1×D)(A \times 1 \times B \times C \times 1 \times D)(A×1×B×C×1×D) then the out tensor will be of shape: (A×B×C×D)(A \times B \times C \times D)(A×B×C×D).

In [91]:
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [93]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [96]:
torch.unsqueeze(x, -1)

tensor([[1],
        [2],
        [3],
        [4]])

In [120]:
data_mean = torch.mean(data,dim=0)
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [122]:
data_var = torch.var(data, dim = 0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [124]:
data_normalized = ( data - data_mean ) / torch.sqrt(data_var)
data_normalized

tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
          1.3422e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])

In [125]:
bad_indexes = target <= 3

In [126]:
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(20))

In [128]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([20, 11])

In [129]:
mid_data  = data[(target > 3) & (target < 7)]
good_data = data[target >= 7]

In [130]:
bad_mean = torch.mean(bad_data,dim=0)
mid_mean = torch.mean(mid_data,dim=0)
good_mean = torch.mean(good_data,dim=0)

In [131]:
for i, args in enumerate(zip(col_list,bad_mean, mid_mean, good_mean)):
  print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42


## Jane Austeen

In [133]:
!wget -o /dev/null https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch4/jane-austen/1342-0.txt

In [134]:
with open('1342-0.txt') as f:
  text = f.read()

In [135]:
lines = text.split('\n')
line = lines[200]
line

'“Impossible, Mr. Bennet, impossible, when I am not acquainted with him'

In [136]:
letter_t = torch.zeros(len(line),128)
letter_t.shape

torch.Size([70, 128])

In [137]:
for i, letter in enumerate(line.lower().strip()):
  letter_index = ord(letter) if ord(letter) < 128 else 0 # only ASCII, higher will be made to point to 0
  letter_t[i][letter_index] = 1

In [139]:
def clean_words(input_str):
  punctuation = '.,;:"!?”“_-'
  word_list = input_str.lower().replace('\n',' ').split()
  word_list = [word.strip(punctuation) for word in word_list]
  return word_list

In [140]:
words_in_line = clean_words(line)
line, words_in_line

('“Impossible, Mr. Bennet, impossible, when I am not acquainted with him',
 ['impossible',
  'mr',
  'bennet',
  'impossible',
  'when',
  'i',
  'am',
  'not',
  'acquainted',
  'with',
  'him'])

In [141]:
word_list = sorted(set(clean_words(text)))
word2index_dict = { word:i for (i,word) in enumerate(word_list)}

In [142]:
len(word2index_dict), word2index_dict['impossible']

(7261, 3394)

In [144]:
word_t = torch.zeros(len(words_in_line), len(word2index_dict))
for i, word in enumerate(words_in_line):
  word_index = word2index_dict[word]
  word_t[i][word_index] = 1
  print('{:2} {:4} {}'.format(i,word_index,word))

print(word_t.shape)

 0 3394 impossible
 1 4305 mr
 2  813 bennet
 3 3394 impossible
 4 7078 when
 5 3315 i
 6  415 am
 7 4436 not
 8  239 acquainted
 9 7148 with
10 3215 him
torch.Size([11, 7261])


## Tehtäviä

### Kuvat

In [24]:
!wget -o /dev/null https://cdn.britannica.com/69/65969-050-8E4B0AB9/Orangutan.jpg
!wget -o /dev/null https://files.worldwildlife.org/wwfcmsprod/images/Blue_Whale/hero_small/gex0x01aq_shutterstock_764499823.jpg -O whale.jpg

In [25]:
oranki_arr = imageio.imread('Orangutan.jpg')
valas_arr = imageio.imread('whale.jpg')

In [26]:
oranki_arr.shape, valas_arr.shape

((1530, 1600, 3), (480, 640, 3))

In [27]:
oranki = torch.from_numpy(oranki_arr)
valas = torch.from_numpy(valas_arr)

In [28]:
oranki = oranki.permute(2,0,1)
valas = valas.permute(2,0,1)

In [29]:
oranki.shape, valas.shape

(torch.Size([3, 1530, 1600]), torch.Size([3, 480, 640]))

In [30]:
oranki.dtype, valas.dtype

(torch.uint8, torch.uint8)

In [31]:
oranki = oranki.float()
valas = valas.float()

In [32]:
oranki = oranki / 255.0
valas = valas / 255.0

In [23]:
oranki.mean(), oranki[0].mean(), oranki[1].mean(), oranki[2].mean()

(tensor(0.4460), tensor(0.5359), tensor(0.4684), tensor(0.3336))

In [33]:
valas.mean(), valas[0].mean(), valas[1].mean(), valas[2].mean()

(tensor(0.1247), tensor(0.0305), tensor(0.1267), tensor(0.2169))

### Teksti

In [38]:
import re

In [71]:
!rm koodi.py

In [72]:
!wget -o /dev/null https://raw.githubusercontent.com/OmkarPathak/Python-Programs/master/Programs/P75_TicTacToe.py -O koodi.py

In [73]:
with open('koodi.py') as f:
  koodi = f.read()

### ASCII to onehot

In [74]:
koodi

"# Author: OMKAR PATHAK\n\n# A simple example of tic tac toe game\n\n# For storing user choices\nchoices = []\n\n# For initializing the board with numbers\nfor i in range(0, 9):\n    choices.append(str(i))\n\nfirstPlayer = True\nwinner = False\niterations = 0      # To terminate the loop\n\n# For drawing board on to the terminal\ndef printBoard():\n    print('\\n=============')\n    print('| ' + choices[0] + ' | ' + choices[1] + ' | ' + choices[2] + ' |')\n    print('=============')\n    print('| ' + choices[3] + ' | ' + choices[4] + ' | ' + choices[5] + ' |')\n    print('=============')\n    print('| ' + choices[6] + ' | ' + choices[7] + ' | ' + choices[8] + ' |')\n    print('=============\\n')\n\n# Play the game while the winner is not decided or the game is drawn\nwhile not winner and iterations < 9:\n    printBoard()\n\n    iterations += 1\n\n    if firstPlayer == True:\n        print('Player 1: ', end = '')\n    else:\n        print('Player 2: ', end = '')\n\n    try:\n        pla

In [75]:
rivit = koodi.split('\n')
len(rivit)

76

In [79]:
rivit = [re.sub(r'[^a-zA-Z0-9_]+',' ',item.strip()) for item in rivit] 


In [80]:
rivi = rivit[50]
rivi

'choices playerInput O '

In [81]:
kirjaimet = torch.zeros(len(rivi),128)
kirjaimet.shape

torch.Size([22, 128])

In [82]:
for i, kirjain in enumerate(rivi.lower().strip()):
  kirjain_index = ord(kirjain) if ord(kirjain) < 128 else 0
  kirjaimet[i][kirjain_index] = 1

In [83]:
kirjaimet[1]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

In [88]:
maxi = len(rivit[0])
for r in rivit:
  if len(r) > maxi:
    maxi = len(r)
maxi

75

In [89]:
kaikki_rivit_onehot = torch.zeros(len(rivit),maxi,128)

In [90]:
for rivi_i,rivi in enumerate(rivit):
  for kirjain_rivi, kirjain in enumerate(rivi.lower().strip()):
    kirjain_index = ord(kirjain) if ord(kirjain) < 128 else 0
    kaikki_rivit_onehot[rivi_i][kirjain_rivi][kirjain_index] = 1

In [92]:
kaikki_rivit_onehot.shape

torch.Size([76, 75, 128])

In [105]:
kaikki_rivit_onehot[23].shape

torch.Size([75, 128])

In [103]:
ascii = torch.argmax(kaikki_rivit_onehot[23][0]).item()
chr(ascii)

'p'

### From one-hot to ascii

In [117]:
rivi_merkkeina = ""

for rivi in kaikki_rivit_onehot:
  for lause in rivi:
    ascii = torch.argmax(lause).item()
    if ascii != 0: 
      rivi_merkkeina += chr(torch.argmax(lause).item())
  rivi_merkkeina += "\n"

print(rivi_merkkeina)

author omkar pathak

a simple example of tic tac toe game

for storing user choices
choices

for initializing the board with numbers
for i in range 0 9
choices append str i

firstplayer true
winner false
iterations 0 to terminate the loop

for drawing board on to the terminal
def printboard
print n
print choices 0 choices 1 choices 2
print
print choices 3 choices 4 choices 5
print
print choices 6 choices 7 choices 8
print n

play the game while the winner is not decided or the game is drawn
while not winner and iterations 9
printboard

iterations 1

if firstplayer true
print player 1 end
else
print player 2 end

try
playerinput int input
except
print please enter a valid number from the board
continue

check if userinput already has x or o
if choices playerinput x or choices playerinput o
print illegal move try again
continue

if firstplayer
choices playerinput x
else
choices playerinput o

firstplayer not firstplayer

winning conditions
for index in range 0 3
for 0 1 2 3 4 5 6 7 8
if 

In [118]:
rivit

[' Author OMKAR PATHAK',
 '',
 ' A simple example of tic tac toe game',
 '',
 ' For storing user choices',
 'choices ',
 '',
 ' For initializing the board with numbers',
 'for i in range 0 9 ',
 'choices append str i ',
 '',
 'firstPlayer True',
 'winner False',
 'iterations 0 To terminate the loop',
 '',
 ' For drawing board on to the terminal',
 'def printBoard ',
 'print n ',
 'print choices 0 choices 1 choices 2 ',
 'print ',
 'print choices 3 choices 4 choices 5 ',
 'print ',
 'print choices 6 choices 7 choices 8 ',
 'print n ',
 '',
 ' Play the game while the winner is not decided or the game is drawn',
 'while not winner and iterations 9 ',
 'printBoard ',
 '',
 'iterations 1',
 '',
 'if firstPlayer True ',
 'print Player 1 end ',
 'else ',
 'print Player 2 end ',
 '',
 'try ',
 'playerInput int input ',
 'except ',
 'print Please enter a valid number from the board ',
 'continue',
 '',
 ' Check if userInput already has X or O ',
 'if choices playerInput X or choices playerInput