<a href="https://colab.research.google.com/github/harttu/docs/blob/master/PyTorchTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

Luodaan tensori 0:sta 23:än. Muokataan tensorin dimensiot seuraavaksi: 2 matriisia, joissa 3 riviä ja 4 saraketta.

In [43]:
some_t = torch.arange(0,2*3*4)
some_t.shape

torch.Size([24])

In [44]:
some_t = torch.reshape(some_t,(2,3,4))
some_t.shape

torch.Size([2, 3, 4])

In [46]:
some_t

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Storagessa on tensorin arvot muistissa

In [39]:
some_t_storage = some_t.storage()
for x in some_t.storage():
    print(x, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [56]:
transpose_t = some_t.transpose(0,2)

In [57]:
transpose_t

tensor([[[ 0, 12],
         [ 4, 16],
         [ 8, 20]],

        [[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]]])

In [ ]:
transpose_t.shape

In [54]:
some_t.stride()

(12, 4, 1)

In [55]:
transpose_t.stride()

(1, 4, 12)

Kun tensori muutetaan contiguousiksi, niin tiedot ovat rivi riviltä

In [60]:
some_t.is_contiguous()

True

In [61]:
transpose_t.is_contiguous()

False

In [65]:
transpose_t.contiguous().storage()

 0
 12
 4
 16
 8
 20
 1
 13
 5
 17
 9
 21
 2
 14
 6
 18
 10
 22
 3
 15
 7
 19
 11
 23
[torch.LongStorage of size 24]

In [66]:
transpose_t.contiguous().stride()

(6, 2, 1)

##Tehtäviä

1)

In [78]:
a = torch.tensor(list(range(9)))

In [79]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
a.size()

torch.Size([9])

In [81]:
a.storage_offset()

0

In [82]:
a.stride()

(1,)

In [83]:
b = a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [85]:
id(a.storage())==id(b.storage())

True

In [87]:
c = b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

In [88]:
c.storage_offset()

4

In [89]:
c.stride()

(3, 1)

2)

In [91]:
torch.sqrt(torch.tensor(2))

tensor(1.4142)

In [92]:
torch.sqrt(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [97]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
a = a.double()
torch.sqrt_(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
       dtype=torch.float64)

In [102]:
a

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
       dtype=torch.float64)

In [94]:
import math

In [96]:
math.sqrt(torch.tensor(2))

1.4142135623730951

In [95]:
math.sqrt(a)

ValueError: ignored